"""
This type stub file was generated by pyright.
"""

from .. import ecore as Ecore
from . import xmi
from .resource import URI
from .resource import AbstractURIConverter
from .resource import HttpURIConverter
from .resource import Resource
from .resource import ResourceSet
from .resource import global_registry
from .resource import global_uri_converter
from .resource import global_uri_mapper

__all__ = ['ResourceSet', 'Resource', 'URI', 'global_registry', 'global_uri_mapper', 'global_uri_converter', 'AbstractURIConverter']
