"""
This type stub file was generated by pyright.
"""

from .resource import AbstractURIConverter, HttpURIConverter, Resource, ResourceSet, URI, global_registry, global_uri_converter, global_uri_mapper
from . import xmi
from .. import ecore as Ecore

__all__ = ['ResourceSet', 'Resource', 'URI', 'global_registry', 'global_uri_mapper', 'global_uri_converter', 'AbstractURIConverter']
