"""
This type stub file was generated by pyright.
"""

from .client import InfluxDBClient

"""DataFrame client for InfluxDB v0.8."""
class DataFrameClient(InfluxDBClient):
    """Primary defintion of the DataFrameClient for v0.8.

    The ``DataFrameClient`` object holds information necessary to connect
    to InfluxDB. Requests can be made to InfluxDB directly through the client.
    The client reads and writes from pandas DataFrames.
    """
    def __init__(self, ignore_nan=..., *args, **kwargs) -> None:
        """Initialize an instance of the DataFrameClient."""
        ...

    def write_points(self, data, *args, **kwargs): # -> Literal[True]:
        """Write to multiple time series names.

        :param data: A dictionary mapping series names to pandas DataFrames
        :param time_precision: [Optional, default 's'] Either 's', 'm', 'ms'
            or 'u'.
        :param batch_size: [Optional] Value to write the points in batches
            instead of all at one time. Useful for when doing data dumps from
            one database to another or when doing a massive write operation
        :type batch_size: int
        """
        ...

    def write_points_with_precision(self, data, time_precision=...): # -> Literal[True]:
        """Write to multiple time series names.

        DEPRECATED
        """
        ...

    def query(self, query, time_precision=..., chunked=...): # -> list[Any] | Any | DataFrame | dict[Any, Any]:
        """Query data into DataFrames.

        Returns a DataFrame for a single time series and a map for multiple
        time series with the time series as value and its name as key.

        :param time_precision: [Optional, default 's'] Either 's', 'm', 'ms'
            or 'u'.
        :param chunked: [Optional, default=False] True if the data shall be
            retrieved in chunks, False otherwise.
        """
        ...
