version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "scene-connect/dependabot-reviewers"
    schedule:
      day: "monday"
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
  - package-ecosystem: "pip"
    allow:
      - dependency-type: all
    directory: "/"
    reviewers:
      - "scene-connect/dependabot-reviewers"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
    insecure-external-code-execution: allow # apparently pip executes code see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#insecure-external-code-execution
