"""
This type stub file was generated by pyright.
"""

"""Module to generate chunked JSON replies."""
def loads(s): # -> Generator[Any, Any, None]:
    """Generate a sequence of JSON values from a string."""
    ...
