"""
This type stub file was generated by pyright.
"""

"""Exception handler for InfluxDBClient."""
class InfluxDBClientError(Exception):
    """Raised when an error occurs in the request."""
    def __init__(self, content, code=...) -> None:
        """Initialize the InfluxDBClientError handler."""
        ...



class InfluxDBServerError(Exception):
    """Raised when a server error occurs."""
    def __init__(self, content) -> None:
        """Initialize the InfluxDBServerError handler."""
        ...
