"""
This type stub file was generated by pyright.
"""

from enum import Enum
from enum import unique

from pyecore.resources.resource import Resource

"""
Temporary replace xmi.py from pyEcore with our own as multi-valued attributed values are not correctly read from the
xmi file. In pyEcore 0.13 + 0.14 they used () tuple notation instead of [] for multi-valued attribute values causing it to return a
generator for those values instead of a list of values.

The xmi module introduces XMI resource and XMI parsing.
"""
XSI = ...
XSI_URL = ...
XMI = ...
XMI_URL = ...
@unique
class XMIOptions(Enum):
    OPTION_USE_XMI_TYPE = ...
    SERIALIZE_DEFAULT_VALUES = ...


class XMIResource(Resource):
    def __init__(self, uri=..., use_uuid=...) -> None:
        ...

    def load(self, options=...): # -> None:
        ...

    def xsi_type_url(self): # -> Literal['http://www.omg.org/XMI', 'http://www.w3.org/2001/XMLSchema-instance']:
        ...

    @staticmethod
    def extract_namespace(tag): # -> tuple[Any, Any]:
        ...

    def register_nsmap(self, prefix, uri): # -> None:
        ...

    def register_eobject_epackage(self, eobj): # -> None:
        ...

    def save(self, output=..., options=...): # -> None:
        ...
