"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
esdlVersion = ...
class EcoreDocumentation:
     """This class loads the dynamic meta-model and returns the documentation for attributes as these are
    not present in the static meta-model (e.g. in the classes that are generated in esdl.py)"""
     def __init__(self, esdlEcoreFile=...) -> None:
          ...

     def get_doc(self, className, attributeName):
          """ Returns the documentation of an attribute from the dynamic meta model,
        because the static meta model does not contain attribute documentation"""
          ...

     def get_unit(self, className: str, attributeName: str) -> str:
          """
        :value: EmodelElement (e.g. EObject) that has an annotation attached
        :returns: The unit attached to this annotation or empty string
        """
          ...

     def get_esdl_version(self):
          ...
