# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lifecycle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0flifecycle.proto"2\n\x13\x45nvironmentVariable\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t"k\n\x12ModelConfiguration\x12\x0f\n\x07modelID\x18\x01 \x01(\t\x12\x10\n\x08imageUrl\x18\x02 \x01(\t\x12\x32\n\x14\x65nvironmentVariables\x18\x03 \x03(\x0b\x32\x14.EnvironmentVariable"l\n\x0c\x44\x65ployModels\x12\x13\n\x0bsimulatorId\x18\x01 \x01(\t\x12\x30\n\x13modelConfigurations\x18\x02 \x03(\x0b\x32\x13.ModelConfiguration\x12\x15\n\rkeepLogsHours\x18\x03 \x01(\x01"\x14\n\x12ReadyForProcessing"\r\n\x0bModelsReady"*\n\x0fModelParameters\x12\x17\n\x0fparameters_dict\x18\x01 \x01(\t"\x0f\n\rParameterized""\n\x07NewStep\x12\x17\n\x0fparameters_dict\x18\x01 \x01(\t"\x12\n\x10\x43\x61lculationsDone"&\n\rErrorOccurred\x12\x15\n\rerror_message\x18\x01 \x01(\t"\x10\n\x0eSimulationDone"7\n\x0eUnhealthyModel\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.UnhealthyModelStatus"J\n\x12ModelHasTerminated\x12"\n\x06status\x18\x01 \x01(\x0e\x32\x12.TerminationStatus\x12\x10\n\x08\x65xitCode\x18\x02 \x01(\x05"\x19\n\x17\x41llModelsHaveTerminated*&\n\x14UnhealthyModelStatus\x12\x0e\n\nNOPROGRESS\x10\x00*0\n\x11TerminationStatus\x12\x0f\n\x0bSUCCESSFULL\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "lifecycle_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _UNHEALTHYMODELSTATUS._serialized_start = 662
    _UNHEALTHYMODELSTATUS._serialized_end = 700
    _TERMINATIONSTATUS._serialized_start = 702
    _TERMINATIONSTATUS._serialized_end = 750
    _ENVIRONMENTVARIABLE._serialized_start = 19
    _ENVIRONMENTVARIABLE._serialized_end = 69
    _MODELCONFIGURATION._serialized_start = 71
    _MODELCONFIGURATION._serialized_end = 178
    _DEPLOYMODELS._serialized_start = 180
    _DEPLOYMODELS._serialized_end = 288
    _READYFORPROCESSING._serialized_start = 290
    _READYFORPROCESSING._serialized_end = 310
    _MODELSREADY._serialized_start = 312
    _MODELSREADY._serialized_end = 325
    _MODELPARAMETERS._serialized_start = 327
    _MODELPARAMETERS._serialized_end = 369
    _PARAMETERIZED._serialized_start = 371
    _PARAMETERIZED._serialized_end = 386
    _NEWSTEP._serialized_start = 388
    _NEWSTEP._serialized_end = 422
    _CALCULATIONSDONE._serialized_start = 424
    _CALCULATIONSDONE._serialized_end = 442
    _ERROROCCURRED._serialized_start = 444
    _ERROROCCURRED._serialized_end = 482
    _SIMULATIONDONE._serialized_start = 484
    _SIMULATIONDONE._serialized_end = 500
    _UNHEALTHYMODEL._serialized_start = 502
    _UNHEALTHYMODEL._serialized_end = 557
    _MODELHASTERMINATED._serialized_start = 559
    _MODELHASTERMINATED._serialized_end = 633
    _ALLMODELSHAVETERMINATED._serialized_start = 635
    _ALLMODELSHAVETERMINATED._serialized_end = 660
# @@protoc_insertion_point(module_scope)
