"""
This type stub file was generated by pyright.
"""

from ..ecore import EDataType
from ..ecore import EStringToStringMapEntry
from ..resources import Resource
from ..resources import global_registry
from .type import ENTITIES
from .type import ENTITY
from .type import ID
from .type import IDREF
from .type import IDREFS
from .type import NMTOKEN
from .type import NMTOKENS
from .type import NOTATION
from .type import AnySimpleType
from .type import AnyType
from .type import AnyURI
from .type import Base64Binary
from .type import Boolean
from .type import BooleanObject
from .type import Byte
from .type import ByteObject
from .type import Date
from .type import DateTime
from .type import Decimal
from .type import Double
from .type import DoubleObject
from .type import Duration
from .type import ENTITIESBase
from .type import Float
from .type import FloatObject
from .type import GDay
from .type import GMonth
from .type import GMonthDay
from .type import GYear
from .type import GYearMonth
from .type import HexBinary
from .type import IDREFSBase
from .type import Int
from .type import Integer
from .type import IntObject
from .type import Language
from .type import Long
from .type import LongObject
from .type import Name
from .type import NCName
from .type import NegativeInteger
from .type import NMTOKENSBase
from .type import NonNegativeInteger
from .type import NonPositiveInteger
from .type import NormalizedString
from .type import PositiveInteger
from .type import ProcessingInstruction
from .type import QName
from .type import Short
from .type import ShortObject
from .type import SimpleAnyType
from .type import String
from .type import Time
from .type import Token
from .type import UnsignedByte
from .type import UnsignedByteObject
from .type import UnsignedInt
from .type import UnsignedIntObject
from .type import UnsignedLong
from .type import UnsignedShort
from .type import UnsignedShortObject
from .type import XMLTypeDocumentRoot
from .type import eClass
from .type import eClassifiers
from .type import getEClassifier
from .type import name
from .type import nsPrefix
from .type import nsURI

"""
Implementation of EMF XMLTypes. This implementation is not automatically
registered in the 'global_registry' if directly imported. The automatic
registration is performed when 'resources' is used.

This implementation had been almost fully generated using pyecoregen. The only
manual intervention required are:
 - addition of the missing import for 'EDataType' and 'EStringToStringMapEntry'
   in '__init__.py'
 - addition of 'from_string' and 'to_string' lambdas for required types

Still missing are a proper translation for Java types:
 - 'javax.xml.datatype.XMLGregorianCalendar'
 - 'javax.xml.datatype.Duration'
 - 'javax.xml.namespace.QName'
"""
__all__ = ['AnySimpleType', 'AnyType', 'AnyURI', 'Base64Binary', 'Boolean', 'BooleanObject', 'Byte', 'ByteObject', 'Date', 'DateTime', 'Decimal', 'Double', 'DoubleObject', 'Duration', 'ENTITIES', 'ENTITIESBase', 'ENTITY', 'Float', 'FloatObject', 'GDay', 'GMonth', 'GMonthDay', 'GYear', 'GYearMonth', 'HexBinary', 'ID', 'IDREF', 'IDREFS', 'IDREFSBase', 'Int', 'Integer', 'IntObject', 'Language', 'Long', 'LongObject', 'Name', 'NCName', 'NegativeInteger', 'NMTOKEN', 'NMTOKENS', 'NMTOKENSBase', 'NonNegativeInteger', 'NonPositiveInteger', 'NormalizedString', 'NOTATION', 'PositiveInteger', 'ProcessingInstruction', 'QName', 'Short', 'ShortObject', 'SimpleAnyType', 'String', 'Time', 'Token', 'UnsignedByte', 'UnsignedByteObject', 'UnsignedInt', 'UnsignedIntObject', 'UnsignedLong', 'UnsignedShort', 'UnsignedShortObject', 'XMLTypeDocumentRoot']
eSubpackages = ...
eSuperPackage = ...
otherClassifiers = ...
xmltypes_resource = ...
