"""
This type stub file was generated by pyright.
"""

from ..ecore import EDataType, EStringToStringMapEntry
from ..resources import Resource, global_registry
from .type import AnySimpleType, AnyType, AnyURI, Base64Binary, Boolean, BooleanObject, Byte, ByteObject, Date, DateTime, Decimal, Double, DoubleObject, Duration, ENTITIES, ENTITIESBase, ENTITY, Float, FloatObject, GDay, GMonth, GMonthDay, GYear, GYearMonth, HexBinary, ID, IDREF, IDREFS, IDREFSBase, Int, IntObject, Integer, Language, Long, LongObject, NCName, NMTOKEN, NMTOKENS, NMTOKENSBase, NOTATION, Name, NegativeInteger, NonNegativeInteger, NonPositiveInteger, NormalizedString, PositiveInteger, ProcessingInstruction, QName, Short, ShortObject, SimpleAnyType, String, Time, Token, UnsignedByte, UnsignedByteObject, UnsignedInt, UnsignedIntObject, UnsignedLong, UnsignedShort, UnsignedShortObject, XMLTypeDocumentRoot, eClass, eClassifiers, getEClassifier, name, nsPrefix, nsURI

"""
Implementation of EMF XMLTypes. This implementation is not automatically
registered in the 'global_registry' if directly imported. The automatic
registration is performed when 'resources' is used.

This implementation had been almost fully generated using pyecoregen. The only
manual intervention required are:
 - addition of the missing import for 'EDataType' and 'EStringToStringMapEntry'
   in '__init__.py'
 - addition of 'from_string' and 'to_string' lambdas for required types

Still missing are a proper translation for Java types:
 - 'javax.xml.datatype.XMLGregorianCalendar'
 - 'javax.xml.datatype.Duration'
 - 'javax.xml.namespace.QName'
"""
__all__ = ['AnySimpleType', 'AnyType', 'AnyURI', 'Base64Binary', 'Boolean', 'BooleanObject', 'Byte', 'ByteObject', 'Date', 'DateTime', 'Decimal', 'Double', 'DoubleObject', 'Duration', 'ENTITIES', 'ENTITIESBase', 'ENTITY', 'Float', 'FloatObject', 'GDay', 'GMonth', 'GMonthDay', 'GYear', 'GYearMonth', 'HexBinary', 'ID', 'IDREF', 'IDREFS', 'IDREFSBase', 'Int', 'Integer', 'IntObject', 'Language', 'Long', 'LongObject', 'Name', 'NCName', 'NegativeInteger', 'NMTOKEN', 'NMTOKENS', 'NMTOKENSBase', 'NonNegativeInteger', 'NonPositiveInteger', 'NormalizedString', 'NOTATION', 'PositiveInteger', 'ProcessingInstruction', 'QName', 'Short', 'ShortObject', 'SimpleAnyType', 'String', 'Time', 'Token', 'UnsignedByte', 'UnsignedByteObject', 'UnsignedInt', 'UnsignedIntObject', 'UnsignedLong', 'UnsignedShort', 'UnsignedShortObject', 'XMLTypeDocumentRoot']
eSubpackages = ...
eSuperPackage = ...
otherClassifiers = ...
xmltypes_resource = ...
