"""
This type stub file was generated by pyright.
"""

SLICE_ALL = ...
def insert(self, index, key): # -> None:
    """Adds an element at a dedicated position in an OrderedSet.

    This implementation is meant for the OrderedSet from the ordered_set
    package only.
    """
    ...

def pop(self, index=...): # -> Literal[-1]:
    """Removes an element at the tail of the OrderedSet or at a dedicated
    position.

    This implementation is meant for the OrderedSet from the ordered_set
    package only.
    """
    ...

def __setitem__(self, index, item): # -> None:
    ...

def __getitem__(self, index):
    ...

def __delitem__(self, index): # -> None:
    ...

def subcopy(self, subitems):
    """
    This method is here mainly for overriding
    """
    ...
