"""
This type stub file was generated by pyright.
"""

from .notification import EObserver

"""
This module gathers utility classes and functions that can ease metamodel and
model manipulation.
"""
class DynamicEPackage(EObserver):
    """A DynamicEPackage gives the ability to directly handle metaclasses
    from a metamodel as if it were a statically generated EPackage.

    Usage from an existing dynamic EPackage named 'myroot' that defines two
    EClass: 'A' and 'B'
    >>> from pyecore.utils import DynamicEPackage
    >>> MyAPI = DynamicEPackage(myroot)
    >>> MyAPI.A
    <EClass name="A">
    >>> a = MyAPI.A()
    >>> a
    <pyecore.ecore.A object at 0x7f118de363c8>
    """
    def __init__(self, package) -> None:
        ...

    def notifyChanged(self, notification): # -> None:
        ...



def dispatch(func): # -> Callable[..., Any]:
    ...

def alias(name, feature, eclass=...): # -> None:
    ...
