# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: healthcheck.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "healthcheck.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(  # type:ignore[reportUnkownVariableType]
    b'\n\x11healthcheck.proto"_\n\x11PingHealthSOToMSO\x12\x1e\n\x07healthy\x18\x01 \x01(\x0e\x32\r.HealthStatus\x12\x0f\n\x07reasons\x18\x02 \x03(\t\x12\x19\n\x11\x61\x63tiveSimulations\x18\x03 \x03(\t"D\n\x11PongHealthMSOToSO\x12\x1e\n\x07healthy\x18\x01 \x01(\x0e\x32\r.HealthStatus\x12\x0f\n\x07reasons\x18\x02 \x03(\t"G\n\x14PingHealthMSOToModel\x12\x1e\n\x07healthy\x18\x01 \x01(\x0e\x32\r.HealthStatus\x12\x0f\n\x07reasons\x18\x02 \x03(\t"z\n\x14PongHealthModelToMSO\x12\x1e\n\x07healthy\x18\x01 \x01(\x0e\x32\r.HealthStatus\x12\x0f\n\x07reasons\x18\x02 \x03(\t\x12\x14\n\x0cnumberOfBids\x18\x03 \x01(\x05\x12\x1b\n\x13numberOfAllocations\x18\x04 \x01(\x05**\n\x0cHealthStatus\x12\x0b\n\x07HEALTHY\x10\x00\x12\r\n\tUNHEALTHY\x10\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(  # type:ignore[reportUnkownMemberType]
    DESCRIPTOR, _globals  # type:ignore[reportUnkownVariableType]
)
_builder.BuildTopDescriptorsAndMessages(  # type:ignore[reportUnkownMemberType]
    DESCRIPTOR, "healthcheck_pb2", _globals  # type:ignore[reportUnkownVariableType]
)
if not _descriptor._USE_C_DESCRIPTORS:  # type:ignore[reportPrivateUsage]
    DESCRIPTOR._loaded_options = None
    _globals["_HEALTHSTATUS"]._serialized_start = 385
    _globals["_HEALTHSTATUS"]._serialized_end = 427
    _globals["_PINGHEALTHSOTOMSO"]._serialized_start = 21
    _globals["_PINGHEALTHSOTOMSO"]._serialized_end = 116
    _globals["_PONGHEALTHMSOTOSO"]._serialized_start = 118
    _globals["_PONGHEALTHMSOTOSO"]._serialized_end = 186
    _globals["_PINGHEALTHMSOTOMODEL"]._serialized_start = 188
    _globals["_PINGHEALTHMSOTOMODEL"]._serialized_end = 259
    _globals["_PONGHEALTHMODELTOMSO"]._serialized_start = 261
    _globals["_PONGHEALTHMODELTOMSO"]._serialized_end = 383
# @@protoc_insertion_point(module_scope)
